# Generated by Django 3.2.25 on 2025-06-09 21:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafeteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre comercial de la cafetería', max_length=120, unique=True)),
                ('imagen', models.ImageField(blank=True, help_text='Foto de la fachada, logo o ambiente', null=True, upload_to='cafeterias/')),
                ('estrellas_google', models.DecimalField(decimal_places=1, help_text='Puntuación pública de Google (0 − 5)', max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('rating_comida', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calidad de la comida')),
                ('rating_atencion', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Atención del personal')),
                ('rating_ubicacion', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Ubicación / Accesibilidad')),
                ('descripcion', models.TextField(blank=True, help_text='Breve reseña o comentario')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
