# Generated by Django 3.2.25 on 2025-06-19 17:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeterias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeteria',
            name='rating_precio',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='cafeteria',
            name='rating_ubicacion',
            field=models.URLField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Ubicación'),
        ),
    ]
