# Generated by Django 3.2.25 on 2025-06-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeterias', '0002_auto_20250619_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeteria',
            name='rating_ubicacion',
            field=models.URLField(help_text='Enlace a la ubicación (ej. Google Maps)', verbose_name='Ubicación'),
        ),
    ]
