# Generated by Django 3.2.25 on 2025-06-19 17:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeterias', '0003_alter_cafeteria_rating_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeteria',
            name='estrellas_google',
            field=models.DecimalField(decimal_places=1, help_text='Puntuación personal (0 − 5)', max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='cafeteria',
            name='imagen',
            field=models.URLField(blank=True, help_text='Foto de la fachada, logo o ambiente', null=True),
        ),
    ]
