# Generated by Django 3.2.25 on 2025-06-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeterias', '0004_auto_20250619_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafeteria',
            old_name='estrellas_google',
            new_name='estrellas_puntuacion',
        ),
        migrations.AlterField(
            model_name='cafeteria',
            name='imagen',
            field=models.URLField(blank=True, help_text='Imagen de referencia', null=True),
        ),
        migrations.AlterField(
            model_name='cafeteria',
            name='nombre',
            field=models.CharField(help_text='Nombre de la cafetería', max_length=120, unique=True),
        ),
    ]
